package com.voidwhile.system.entity;

import java.util.Date;

public class Job {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.job_id
     *
     * @mbg.generated
     */
    private Long jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.instance
     *
     * @mbg.generated
     */
    private String instance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.job_interval
     *
     * @mbg.generated
     */
    private Integer jobInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.next_exec_time
     *
     * @mbg.generated
     */
    private Date nextExecTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.job_status
     *
     * @mbg.generated
     */
    private Integer jobStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.fcd
     *
     * @mbg.generated
     */
    private Date fcd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.job_id
     *
     * @return the value of sys_job.job_id
     *
     * @mbg.generated
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.job_id
     *
     * @param jobId the value for sys_job.job_id
     *
     * @mbg.generated
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.title
     *
     * @return the value of sys_job.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.title
     *
     * @param title the value for sys_job.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.instance
     *
     * @return the value of sys_job.instance
     *
     * @mbg.generated
     */
    public String getInstance() {
        return instance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.instance
     *
     * @param instance the value for sys_job.instance
     *
     * @mbg.generated
     */
    public void setInstance(String instance) {
        this.instance = instance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.job_interval
     *
     * @return the value of sys_job.job_interval
     *
     * @mbg.generated
     */
    public Integer getJobInterval() {
        return jobInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.job_interval
     *
     * @param jobInterval the value for sys_job.job_interval
     *
     * @mbg.generated
     */
    public void setJobInterval(Integer jobInterval) {
        this.jobInterval = jobInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.next_exec_time
     *
     * @return the value of sys_job.next_exec_time
     *
     * @mbg.generated
     */
    public Date getNextExecTime() {
        return nextExecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.next_exec_time
     *
     * @param nextExecTime the value for sys_job.next_exec_time
     *
     * @mbg.generated
     */
    public void setNextExecTime(Date nextExecTime) {
        this.nextExecTime = nextExecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.job_status
     *
     * @return the value of sys_job.job_status
     *
     * @mbg.generated
     */
    public Integer getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.job_status
     *
     * @param jobStatus the value for sys_job.job_status
     *
     * @mbg.generated
     */
    public void setJobStatus(Integer jobStatus) {
        this.jobStatus = jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.fcd
     *
     * @return the value of sys_job.fcd
     *
     * @mbg.generated
     */
    public Date getFcd() {
        return fcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.fcd
     *
     * @param fcd the value for sys_job.fcd
     *
     * @mbg.generated
     */
    public void setFcd(Date fcd) {
        this.fcd = fcd;
    }
}