package com.voidwhile.system.entity;

import java.util.Date;

public class JobTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_task.task_id
     *
     * @mbg.generated
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_task.job_id
     *
     * @mbg.generated
     */
    private Long jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_task.instance
     *
     * @mbg.generated
     */
    private String instance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_task.exec_time
     *
     * @mbg.generated
     */
    private Date execTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_task.done_time
     *
     * @mbg.generated
     */
    private Date doneTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_task.task_status
     *
     * @mbg.generated
     */
    private Integer taskStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_task.result_msg
     *
     * @mbg.generated
     */
    private String resultMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_task.fcd
     *
     * @mbg.generated
     */
    private Date fcd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_task.task_id
     *
     * @return the value of sys_job_task.task_id
     *
     * @mbg.generated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_task.task_id
     *
     * @param taskId the value for sys_job_task.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_task.job_id
     *
     * @return the value of sys_job_task.job_id
     *
     * @mbg.generated
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_task.job_id
     *
     * @param jobId the value for sys_job_task.job_id
     *
     * @mbg.generated
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_task.instance
     *
     * @return the value of sys_job_task.instance
     *
     * @mbg.generated
     */
    public String getInstance() {
        return instance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_task.instance
     *
     * @param instance the value for sys_job_task.instance
     *
     * @mbg.generated
     */
    public void setInstance(String instance) {
        this.instance = instance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_task.exec_time
     *
     * @return the value of sys_job_task.exec_time
     *
     * @mbg.generated
     */
    public Date getExecTime() {
        return execTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_task.exec_time
     *
     * @param execTime the value for sys_job_task.exec_time
     *
     * @mbg.generated
     */
    public void setExecTime(Date execTime) {
        this.execTime = execTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_task.done_time
     *
     * @return the value of sys_job_task.done_time
     *
     * @mbg.generated
     */
    public Date getDoneTime() {
        return doneTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_task.done_time
     *
     * @param doneTime the value for sys_job_task.done_time
     *
     * @mbg.generated
     */
    public void setDoneTime(Date doneTime) {
        this.doneTime = doneTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_task.task_status
     *
     * @return the value of sys_job_task.task_status
     *
     * @mbg.generated
     */
    public Integer getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_task.task_status
     *
     * @param taskStatus the value for sys_job_task.task_status
     *
     * @mbg.generated
     */
    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_task.result_msg
     *
     * @return the value of sys_job_task.result_msg
     *
     * @mbg.generated
     */
    public String getResultMsg() {
        return resultMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_task.result_msg
     *
     * @param resultMsg the value for sys_job_task.result_msg
     *
     * @mbg.generated
     */
    public void setResultMsg(String resultMsg) {
        this.resultMsg = resultMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_task.fcd
     *
     * @return the value of sys_job_task.fcd
     *
     * @mbg.generated
     */
    public Date getFcd() {
        return fcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_task.fcd
     *
     * @param fcd the value for sys_job_task.fcd
     *
     * @mbg.generated
     */
    public void setFcd(Date fcd) {
        this.fcd = fcd;
    }
}