package com.voidwhile.wx.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlatform<M extends BasePlatform<M>> extends Model<M> implements IBean {

	public void setAppid(java.lang.String appid) {
		set("appid", appid);
	}

	public java.lang.String getAppid() {
		return get("appid");
	}

	public void setSecret(java.lang.String secret) {
		set("secret", secret);
	}

	public java.lang.String getSecret() {
		return get("secret");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setQrcode(java.lang.String qrcode) {
		set("qrcode", qrcode);
	}

	public java.lang.String getQrcode() {
		return get("qrcode");
	}

	public void setSubmsg(java.lang.String submsg) {
		set("submsg", submsg);
	}

	public java.lang.String getSubmsg() {
		return get("submsg");
	}

	public void setAppname(java.lang.String appname) {
		set("appname", appname);
	}

	public java.lang.String getAppname() {
		return get("appname");
	}

}
