package com.voidwhile.market.mapper;

import com.voidwhile.market.entity.AdAdvertType;

public interface AdAdvertTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_ad_advert_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long advertType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_ad_advert_type
     *
     * @mbg.generated
     */
    int insert(AdAdvertType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_ad_advert_type
     *
     * @mbg.generated
     */
    int insertSelective(AdAdvertType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_ad_advert_type
     *
     * @mbg.generated
     */
    AdAdvertType selectByPrimaryKey(Long advertType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_ad_advert_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdAdvertType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_ad_advert_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdAdvertType record);
}