package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.AdAdvert;

public interface AdAdvertMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_ad_advert
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long advertId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_ad_advert
	 * @mbg.generated
	 */
	int insert(AdAdvert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_ad_advert
	 * @mbg.generated
	 */
	int insertSelective(AdAdvert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_ad_advert
	 * @mbg.generated
	 */
	AdAdvert selectByPrimaryKey(Long advertId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_ad_advert
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(AdAdvert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_ad_advert
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(AdAdvert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_ad_advert
	 * @mbg.generated
	 */
	int updateByPrimaryKey(AdAdvert record);

	void deleteByIds(String[] ids);
	
	List<AdAdvert> selectByMap(Map<String, Object> param);
	int countByMap(Map<String, Object> param);
}