package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.CfgSpecification;

public interface CfgSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cfg_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long cfgSftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cfg_specification
     *
     * @mbg.generated
     */
    int insert(CfgSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cfg_specification
     *
     * @mbg.generated
     */
    int insertSelective(CfgSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cfg_specification
     *
     * @mbg.generated
     */
    CfgSpecification selectByPrimaryKey(Long cfgSftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cfg_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CfgSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cfg_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CfgSpecification record);
    
    List<CfgSpecification> selectByMap(Map<String, Object> param);
    
    int countByMap(Map<String, Object> param);
    
    void deleteByIds(String[] ids);
}