package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.CmdBrand;

public interface CmdBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_brand
     *
     * @mbg.generated
     */
    int insert(CmdBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_brand
     *
     * @mbg.generated
     */
    int insertSelective(CmdBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_brand
     *
     * @mbg.generated
     */
    CmdBrand selectByPrimaryKey(Long brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmdBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmdBrand record);
    
    List<CmdBrand> selectByMap(Map<String, Object> param);
    
    int countByMap(Map<String, Object> param);
    
    void deleteByIds(String[] ids);
}