package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.CmdLabel;

public interface CmdLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_label
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_label
     *
     * @mbg.generated
     */
    int insert(CmdLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_label
     *
     * @mbg.generated
     */
    int insertSelective(CmdLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_label
     *
     * @mbg.generated
     */
    CmdLabel selectByPrimaryKey(Long labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_label
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmdLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_label
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmdLabel record);
    
    int deleteByCmdType(Integer cmdType);
    
    int deleteByCmdId(Long cmdId);
    
    List<CmdLabel> selectByCmdId(Long cmdId);
    
    List<CmdLabel> selectByMap(Map<String, Object> param);
    
    
}