package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.CmdSpecification;

public interface CmdSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long sftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_specification
     *
     * @mbg.generated
     */
    int insert(CmdSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_specification
     *
     * @mbg.generated
     */
    int insertSelective(CmdSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_specification
     *
     * @mbg.generated
     */
    CmdSpecification selectByPrimaryKey(Long sftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmdSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmdSpecification record);
    
    List<CmdSpecification> selectByMap(Map<String, Object> param);
    
    void deleteByCmdId(Long cmdId);
}