package com.voidwhile.market.mapper;

import com.voidwhile.market.entity.CmdStatus;

public interface CmdStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cmdStatus);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_status
     *
     * @mbg.generated
     */
    int insert(CmdStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_status
     *
     * @mbg.generated
     */
    int insertSelective(CmdStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_status
     *
     * @mbg.generated
     */
    CmdStatus selectByPrimaryKey(Integer cmdStatus);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmdStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_cmd_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmdStatus record);
}