package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.CmdType;

public interface CmdTypeMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_cmd_type
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer cmdType);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_cmd_type
	 * @mbg.generated
	 */
	int insert(CmdType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_cmd_type
	 * @mbg.generated
	 */
	int insertSelective(CmdType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_cmd_type
	 * @mbg.generated
	 */
	CmdType selectByPrimaryKey(Integer cmdType);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_cmd_type
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(CmdType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_cmd_type
	 * @mbg.generated
	 */
	int updateByPrimaryKey(CmdType record);

	List<CmdType> selectByMap(Map<String, Object> param);
	
	int countByMap(Map<String, Object> param);
	
	void deleteByIds(String[] ids);
}