package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.MbeCollect;

public interface MbeCollectMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_mbe_collect
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long collectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_mbe_collect
	 * @mbg.generated
	 */
	int insert(MbeCollect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_mbe_collect
	 * @mbg.generated
	 */
	int insertSelective(MbeCollect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_mbe_collect
	 * @mbg.generated
	 */
	MbeCollect selectByPrimaryKey(Long collectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_mbe_collect
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MbeCollect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_mbe_collect
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MbeCollect record);

	List<MbeCollect> selectByMap(Map<String, Object> param);

	int countByMap(Map<String, Object> param);
    
    
}