package com.voidwhile.market.mapper;

import com.voidwhile.market.entity.MbeMemberCard;

public interface MbeMemberCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_mbe_member_card
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_mbe_member_card
     *
     * @mbg.generated
     */
    int insert(MbeMemberCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_mbe_member_card
     *
     * @mbg.generated
     */
    int insertSelective(MbeMemberCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_mbe_member_card
     *
     * @mbg.generated
     */
    MbeMemberCard selectByPrimaryKey(Long cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_mbe_member_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MbeMemberCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_mbe_member_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MbeMemberCard record);
}