package com.voidwhile.market.mapper;

import com.voidwhile.market.entity.MbeMember;

public interface MbeMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_mbe_member
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_mbe_member
     *
     * @mbg.generated
     */
    int insert(MbeMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_mbe_member
     *
     * @mbg.generated
     */
    int insertSelective(MbeMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_mbe_member
     *
     * @mbg.generated
     */
    MbeMember selectByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_mbe_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MbeMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_mbe_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MbeMember record);
}