package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.OdrCart;

public interface OdrCartMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_odr_cart
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long cartId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_odr_cart
	 * @mbg.generated
	 */
	int insert(OdrCart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_odr_cart
	 * @mbg.generated
	 */
	int insertSelective(OdrCart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_odr_cart
	 * @mbg.generated
	 */
	OdrCart selectByPrimaryKey(Long cartId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_odr_cart
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(OdrCart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_odr_cart
	 * @mbg.generated
	 */
	int updateByPrimaryKey(OdrCart record);
	
	List<OdrCart> selectByMap(Map<String, Object> param);

	int countByMap(Map<String, Object> param);

	List<OdrCart> selectByMemberId(Long memberId);

	List<OdrCart> selectForSettle(Long memberId);

	Double sum(Long memberId);

	void settle(Long memberId);

	void plus(Long cartId);

	void minus(Long cartId);
}