package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.OdrOrder;

public interface OdrOrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_odr_order
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_odr_order
	 * @mbg.generated
	 */
	int insert(OdrOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_odr_order
	 * @mbg.generated
	 */
	int insertSelective(OdrOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_odr_order
	 * @mbg.generated
	 */
	OdrOrder selectByPrimaryKey(Long orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_odr_order
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(OdrOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_odr_order
	 * @mbg.generated
	 */
	int updateByPrimaryKey(OdrOrder record);

	public List<OdrOrder> findByMap(Map<String, Object> param);

	public int countByMap(Map<String, Object> param);
	
	public void deliver(Long orderId);

	void giveUp(Long memberId);
}