package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.OdrOrderDetail;

public interface OdrOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_odr_order_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_odr_order_detail
     *
     * @mbg.generated
     */
    int insert(OdrOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_odr_order_detail
     *
     * @mbg.generated
     */
    int insertSelective(OdrOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_odr_order_detail
     *
     * @mbg.generated
     */
    OdrOrderDetail selectByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_odr_order_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OdrOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_odr_order_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OdrOrderDetail record);
    
    List<OdrOrderDetail> findByOrderId(Map<String, Object> param);
    int countByOrderId(Map<String, Object> param);
}