package com.voidwhile.market.mapper;

import java.util.List;

import com.voidwhile.market.entity.OdrSettle;

public interface OdrSettleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_odr_settle
     *
     * @mbg.generated
     */
    int deleteByMemberId(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_odr_settle
     *
     * @mbg.generated
     */
    int insert(OdrSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_odr_settle
     *
     * @mbg.generated
     */
    int insertSelective(OdrSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_odr_settle
     *
     * @mbg.generated
     */
    List<OdrSettle> selectByMemberId(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_odr_settle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OdrSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_odr_settle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OdrSettle record);
    
    int countByCartId(Long cartId);
    
    
}