package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.PubImage;

public interface PubImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gxs_pub_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gxs_pub_image
     *
     * @mbg.generated
     */
    int insert(PubImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gxs_pub_image
     *
     * @mbg.generated
     */
    int insertSelective(PubImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gxs_pub_image
     *
     * @mbg.generated
     */
    PubImage selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gxs_pub_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PubImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gxs_pub_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PubImage record);

	List<PubImage> selectByMap(Map<String, Object> param);

	PubImage findById(Integer id);

	

}