package com.voidwhile.market.mapper;

import com.voidwhile.market.entity.RepCmdSupplier;

public interface RepCmdSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_rep_cmd_supplier
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long cmdSupplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_rep_cmd_supplier
     *
     * @mbg.generated
     */
    int insert(RepCmdSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_rep_cmd_supplier
     *
     * @mbg.generated
     */
    int insertSelective(RepCmdSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_rep_cmd_supplier
     *
     * @mbg.generated
     */
    RepCmdSupplier selectByPrimaryKey(Long cmdSupplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_rep_cmd_supplier
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RepCmdSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_rep_cmd_supplier
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RepCmdSupplier record);
}