package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.RepInventory;

public interface RepInventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_rep_inventory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long inventoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_rep_inventory
     *
     * @mbg.generated
     */
    int insert(RepInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_rep_inventory
     *
     * @mbg.generated
     */
    int insertSelective(RepInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_rep_inventory
     *
     * @mbg.generated
     */
    RepInventory selectByPrimaryKey(Long inventoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_rep_inventory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RepInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_rep_inventory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RepInventory record);
    
    List<RepInventory> selectByMap(Map<String, Object> param);
    
    int countByMap(Map<String, Object> param);
}