package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.RepSupplier;

public interface RepSupplierMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_rep_supplier
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long supplierId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_rep_supplier
	 * @mbg.generated
	 */
	int insert(RepSupplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_rep_supplier
	 * @mbg.generated
	 */
	int insertSelective(RepSupplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_rep_supplier
	 * @mbg.generated
	 */
	RepSupplier selectByPrimaryKey(Long supplierId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_rep_supplier
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(RepSupplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mk_rep_supplier
	 * @mbg.generated
	 */
	int updateByPrimaryKey(RepSupplier record);
	
	List<RepSupplier> selectByMap(Map<String, Object> param);
	
	int countByMap(Map<String, Object> param);
	
	void deleteByIds(String[] ids);
}