package com.voidwhile.market.mapper;

import com.voidwhile.market.entity.RunRecommend;

public interface RunRecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_run_recommend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long recomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_run_recommend
     *
     * @mbg.generated
     */
    int insert(RunRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_run_recommend
     *
     * @mbg.generated
     */
    int insertSelective(RunRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_run_recommend
     *
     * @mbg.generated
     */
    RunRecommend selectByPrimaryKey(Long recomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_run_recommend
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RunRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_run_recommend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RunRecommend record);
}