package com.voidwhile.market.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.market.entity.RunSale;

public interface RunSaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_run_sale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long saleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_run_sale
     *
     * @mbg.generated
     */
    int insert(RunSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_run_sale
     *
     * @mbg.generated
     */
    int insertSelective(RunSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_run_sale
     *
     * @mbg.generated
     */
    RunSale selectByPrimaryKey(Long saleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_run_sale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RunSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mk_run_sale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RunSale record);
    
    RunSale getTodaySale(String today);
    
    List<RunSale> selectByMap(Map<String, Object> param);
	
	int countByMap(Map<String, Object> param);
}