package com.voidwhile.market.mapper;

import com.voidwhile.market.entity.WechatUser;

public interface WechatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_wechat_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_wechat_user
     *
     * @mbg.generated
     */
    int insert(WechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_wechat_user
     *
     * @mbg.generated
     */
    int insertSelective(WechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_wechat_user
     *
     * @mbg.generated
     */
    WechatUser selectByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_wechat_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_wechat_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WechatUser record);

	WechatUser findByMemberId(Long memberId);
}