package com.voidwhile.system.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.system.entity.DataBackup;

public interface DataBackupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_backup
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer backupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_backup
     *
     * @mbg.generated
     */
    int insert(DataBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_backup
     *
     * @mbg.generated
     */
    int insertSelective(DataBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_backup
     *
     * @mbg.generated
     */
    DataBackup selectByPrimaryKey(Integer backupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_backup
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DataBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_data_backup
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataBackup record);
    
    List<DataBackup> findByMap(Map<String, Object> param);
    
    int countByMap(Map<String, Object> param);
    
    DataBackup getLastFullBackup();
    
    int getOptType();
    
    void updateOptType(Integer optType);
}