package com.voidwhile.system.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.system.entity.Job;

public interface JobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int insert(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int insertSelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    Job selectByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Job record);
    
    List<Job> findByMap(Map<String,Object> param);
    
    /**
     * 获取待执行工作
     * @return
     */
    List<Job> findExecList();
    
    /**
     * 更新下次执行时间
     * @param jobId
     */
    void updateExecTime(Long jobId);
    
    /**
     * 启用
     * @param jobId
     */
    void start(Long jobId);
    	
    /**
     * 停止
     * @param jobId
     */
    void stop(Long jobId);
}