package com.voidwhile.system.mapper;

import java.util.List;

import com.voidwhile.system.entity.JobTask;

public interface JobTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job_task
     *
     * @mbg.generated
     */
    int insert(JobTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job_task
     *
     * @mbg.generated
     */
    int insertSelective(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job_task
     *
     * @mbg.generated
     */
    JobTask selectByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JobTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JobTask record);
    
    List<JobTask> findExecList();
}