package com.voidwhile.wx.model;

import com.voidwhile.wx.model.base.BaseMbeMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MbeMember extends BaseMbeMember<MbeMember> {
	public static final MbeMember dao = new MbeMember();
}
