package com.voidwhile.wx.model;

import com.voidwhile.wx.model.base.BasePlatform;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Platform extends BasePlatform<Platform> {
	public static final Platform dao = new Platform();
}
