package com.voidwhile.wx.model;

import com.voidwhile.wx.model.base.BaseWechatUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatUser extends BaseWechatUser<WechatUser> {
	public static final WechatUser dao = new WechatUser();
}
