package com.voidwhile.market.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.voidwhile.system.constant.SysConstant;

public class AdAdvert {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_ad_advert.advert_id
	 * @mbg.generated
	 */
	private Long advertId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_ad_advert.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_ad_advert.ad_cmd_id
	 * @mbg.generated
	 */
	private Long adCmdId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_ad_advert.url
	 * @mbg.generated
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_ad_advert.img_path
	 * @mbg.generated
	 */
	private String imgPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_ad_advert.ad_advert_type
	 * @mbg.generated
	 */
	private Integer adAdvertType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_ad_advert.state
	 * @mbg.generated
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_ad_advert.start_time
	 * @mbg.generated
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_ad_advert.end_time
	 * @mbg.generated
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_ad_advert.fcd
	 * @mbg.generated
	 */
	private Date fcd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_ad_advert.description
	 * @mbg.generated
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_ad_advert.advert_id
	 * @return  the value of mk_ad_advert.advert_id
	 * @mbg.generated
	 */
	public Long getAdvertId() {
		return advertId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_ad_advert.advert_id
	 * @param advertId  the value for mk_ad_advert.advert_id
	 * @mbg.generated
	 */
	public void setAdvertId(Long advertId) {
		this.advertId = advertId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_ad_advert.title
	 * @return  the value of mk_ad_advert.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_ad_advert.title
	 * @param title  the value for mk_ad_advert.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_ad_advert.ad_cmd_id
	 * @return  the value of mk_ad_advert.ad_cmd_id
	 * @mbg.generated
	 */
	public Long getAdCmdId() {
		return adCmdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_ad_advert.ad_cmd_id
	 * @param adCmdId  the value for mk_ad_advert.ad_cmd_id
	 * @mbg.generated
	 */
	public void setAdCmdId(Long adCmdId) {
		this.adCmdId = adCmdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_ad_advert.url
	 * @return  the value of mk_ad_advert.url
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_ad_advert.url
	 * @param url  the value for mk_ad_advert.url
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_ad_advert.img_path
	 * @return  the value of mk_ad_advert.img_path
	 * @mbg.generated
	 */
	public String getImgPath() {
		return imgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_ad_advert.img_path
	 * @param imgPath  the value for mk_ad_advert.img_path
	 * @mbg.generated
	 */
	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_ad_advert.ad_advert_type
	 * @return  the value of mk_ad_advert.ad_advert_type
	 * @mbg.generated
	 */
	public Integer getAdAdvertType() {
		return adAdvertType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_ad_advert.ad_advert_type
	 * @param adAdvertType  the value for mk_ad_advert.ad_advert_type
	 * @mbg.generated
	 */
	public void setAdAdvertType(Integer adAdvertType) {
		this.adAdvertType = adAdvertType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_ad_advert.state
	 * @return  the value of mk_ad_advert.state
	 * @mbg.generated
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_ad_advert.state
	 * @param state  the value for mk_ad_advert.state
	 * @mbg.generated
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_ad_advert.start_time
	 * @return  the value of mk_ad_advert.start_time
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd ")
	@JsonFormat(pattern = "yyyy-MM-dd ", timezone = "GMT+8")
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_ad_advert.start_time
	 * @param startTime  the value for mk_ad_advert.start_time
	 * @mbg.generated
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_ad_advert.end_time
	 * @return  the value of mk_ad_advert.end_time
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd ")
	@JsonFormat(pattern = "yyyy-MM-dd ", timezone = "GMT+8")
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_ad_advert.end_time
	 * @param endTime  the value for mk_ad_advert.end_time
	 * @mbg.generated
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_ad_advert.fcd
	 * @return  the value of mk_ad_advert.fcd
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	public Date getFcd() {
		return fcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_ad_advert.fcd
	 * @param fcd  the value for mk_ad_advert.fcd
	 * @mbg.generated
	 */
	public void setFcd(Date fcd) {
		this.fcd = fcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_ad_advert.description
	 * @return  the value of mk_ad_advert.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_ad_advert.description
	 * @param description  the value for mk_ad_advert.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description;
	}
	
	private String cmdName;

	public String getCmdName() {
		return cmdName;
	}

	public void setCmdName(String cmdName) {
		this.cmdName = cmdName;
	}
	
}