package com.voidwhile.market.entity;

public class CfgSpecification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cfg_specification.cfg_sft_id
     *
     * @mbg.generated
     */
    private Long cfgSftId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cfg_specification.sft_name
     *
     * @mbg.generated
     */
    private String sftName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cfg_specification.cfg_sft_id
     *
     * @return the value of mk_cfg_specification.cfg_sft_id
     *
     * @mbg.generated
     */
    public Long getCfgSftId() {
        return cfgSftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cfg_specification.cfg_sft_id
     *
     * @param cfgSftId the value for mk_cfg_specification.cfg_sft_id
     *
     * @mbg.generated
     */
    public void setCfgSftId(Long cfgSftId) {
        this.cfgSftId = cfgSftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cfg_specification.sft_name
     *
     * @return the value of mk_cfg_specification.sft_name
     *
     * @mbg.generated
     */
    public String getSftName() {
        return sftName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cfg_specification.sft_name
     *
     * @param sftName the value for mk_cfg_specification.sft_name
     *
     * @mbg.generated
     */
    public void setSftName(String sftName) {
        this.sftName = sftName;
    }
}