package com.voidwhile.market.entity;

public class CmdBrand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_brand.brand_id
     *
     * @mbg.generated
     */
    private Long brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_brand.brand_name
     *
     * @mbg.generated
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_brand.cmd_type
     *
     * @mbg.generated
     */
    private Integer cmdType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_brand.brand_id
     *
     * @return the value of mk_cmd_brand.brand_id
     *
     * @mbg.generated
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_brand.brand_id
     *
     * @param brandId the value for mk_cmd_brand.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_brand.brand_name
     *
     * @return the value of mk_cmd_brand.brand_name
     *
     * @mbg.generated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_brand.brand_name
     *
     * @param brandName the value for mk_cmd_brand.brand_name
     *
     * @mbg.generated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_brand.cmd_type
     *
     * @return the value of mk_cmd_brand.cmd_type
     *
     * @mbg.generated
     */
    public Integer getCmdType() {
        return cmdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_brand.cmd_type
     *
     * @param cmdType the value for mk_cmd_brand.cmd_type
     *
     * @mbg.generated
     */
    public void setCmdType(Integer cmdType) {
        this.cmdType = cmdType;
    }
}