package com.voidwhile.market.entity;

import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class CmdCommodity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_cmd_commodity.cmd_id
	 * @mbg.generated
	 */
	private Long cmdId;
	/**
	 * 商品名称
	 * @mbg.generated
	 */
	private String cmdName;
	/**
	 * 商品编号
	 * @mbg.generated
	 */
	private String cmdCode;
	/**
	 * 品牌
	 * @mbg.generated
	 */
	private Long cmdBrand;
	/**
	 * 状态 1 下架 2 在售 3 缺货
	 * @mbg.generated
	 */
	private Integer cmdStatus;
	/**
	 * 记录创建时间
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * 上架时间
	 * @mbg.generated
	 */
	private Date putawayTime;
	/**
	 * 保质期
	 * @mbg.generated
	 */
	private String shelfLife;
	/**
	 * 生产日期
	 * @mbg.generated
	 */
	private Date produceDate;
	/**
	 * 有效截止日期
	 * @mbg.generated
	 */
	private Date expirationDate;
	/**
	 * 供应商
	 * @mbg.generated
	 */
	private Long supplierId;
	
	private String imgPath;
	
	private String description;//描述
	
	private CmdStatus status;//状态 
	
	private RepSupplier supplier;//供应商
	
	private CmdBrand brand;//品牌
	
	private List<CmdLabel> labels;//标签
	
	private List<CmdSpecification> sfts;//规格
	
	private List<PubImage> images;//图片
	
	
	public List<PubImage> getImages() {
		return images;
	}

	public void setImages(List<PubImage> images) {
		this.images = images;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	
	public List<CmdLabel> getLabels() {
		return labels;
	}

	public void setLabels(List<CmdLabel> labels) {
		this.labels = labels;
	}

	public List<CmdSpecification> getSfts() {
		return sfts;
	}

	public void setSfts(List<CmdSpecification> sfts) {
		this.sfts = sfts;
	}


	public CmdStatus getStatus() {
		return status;
	}

	public void setStatus(CmdStatus status) {
		this.status = status;
	}

	public RepSupplier getSupplier() {
		return supplier;
	}

	public void setSupplier(RepSupplier supplier) {
		this.supplier = supplier;
	}

	public CmdBrand getBrand() {
		return brand;
	}

	public void setBrand(CmdBrand brand) {
		this.brand = brand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_commodity.cmd_id
	 * @return  the value of mk_cmd_commodity.cmd_id
	 * @mbg.generated
	 */
	public Long getCmdId() {
		return cmdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_commodity.cmd_id
	 * @param cmdId  the value for mk_cmd_commodity.cmd_id
	 * @mbg.generated
	 */
	public void setCmdId(Long cmdId) {
		this.cmdId = cmdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_commodity.cmd_name
	 * @return  the value of mk_cmd_commodity.cmd_name
	 * @mbg.generated
	 */
	public String getCmdName() {
		return cmdName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_commodity.cmd_name
	 * @param cmdName  the value for mk_cmd_commodity.cmd_name
	 * @mbg.generated
	 */
	public void setCmdName(String cmdName) {
		this.cmdName = cmdName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_commodity.cmd_code
	 * @return  the value of mk_cmd_commodity.cmd_code
	 * @mbg.generated
	 */
	public String getCmdCode() {
		return cmdCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_commodity.cmd_code
	 * @param cmdCode  the value for mk_cmd_commodity.cmd_code
	 * @mbg.generated
	 */
	public void setCmdCode(String cmdCode) {
		this.cmdCode = cmdCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_commodity.cmd_brand
	 * @return  the value of mk_cmd_commodity.cmd_brand
	 * @mbg.generated
	 */
	public Long getCmdBrand() {
		return cmdBrand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_commodity.cmd_brand
	 * @param cmdBrand  the value for mk_cmd_commodity.cmd_brand
	 * @mbg.generated
	 */
	public void setCmdBrand(Long cmdBrand) {
		this.cmdBrand = cmdBrand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_commodity.cmd_status
	 * @return  the value of mk_cmd_commodity.cmd_status
	 * @mbg.generated
	 */
	public Integer getCmdStatus() {
		return cmdStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_commodity.cmd_status
	 * @param cmdStatus  the value for mk_cmd_commodity.cmd_status
	 * @mbg.generated
	 */
	public void setCmdStatus(Integer cmdStatus) {
		this.cmdStatus = cmdStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_commodity.create_time
	 * @return  the value of mk_cmd_commodity.create_time
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_commodity.create_time
	 * @param createTime  the value for mk_cmd_commodity.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_commodity.putaway_time
	 * @return  the value of mk_cmd_commodity.putaway_time
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	public Date getPutawayTime() {
		return putawayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_commodity.putaway_time
	 * @param putawayTime  the value for mk_cmd_commodity.putaway_time
	 * @mbg.generated
	 */
	public void setPutawayTime(Date putawayTime) {
		this.putawayTime = putawayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_commodity.Shelf_life
	 * @return  the value of mk_cmd_commodity.Shelf_life
	 * @mbg.generated
	 */
	public String getShelfLife() {
		return shelfLife;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_commodity.Shelf_life
	 * @param shelfLife  the value for mk_cmd_commodity.Shelf_life
	 * @mbg.generated
	 */
	public void setShelfLife(String shelfLife) {
		this.shelfLife = shelfLife;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_commodity.produce_date
	 * @return  the value of mk_cmd_commodity.produce_date
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	public Date getProduceDate() {
		return produceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_commodity.produce_date
	 * @param produceDate  the value for mk_cmd_commodity.produce_date
	 * @mbg.generated
	 */
	public void setProduceDate(Date produceDate) {
		this.produceDate = produceDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_commodity.expiration_date
	 * @return  the value of mk_cmd_commodity.expiration_date
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	public Date getExpirationDate() {
		return expirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_commodity.expiration_date
	 * @param expirationDate  the value for mk_cmd_commodity.expiration_date
	 * @mbg.generated
	 */
	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_commodity.supplier_id
	 * @return  the value of mk_cmd_commodity.supplier_id
	 * @mbg.generated
	 */
	public Long getSupplierId() {
		return supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_commodity.supplier_id
	 * @param supplierId  the value for mk_cmd_commodity.supplier_id
	 * @mbg.generated
	 */
	public void setSupplierId(Long supplierId) {
		this.supplierId = supplierId;
	}

	public String getImgPath() {
		return imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}
}