package com.voidwhile.market.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class CmdPrice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_cmd_price.price_id
	 * @mbg.generated
	 */
	private Long priceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_cmd_price.cmd_id
	 * @mbg.generated
	 */
	private Long cmdId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_cmd_price.price
	 * @mbg.generated
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_cmd_price.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_cmd_price.price_type
	 * @mbg.generated
	 */
	private Integer priceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_cmd_price.event_id
	 * @mbg.generated
	 */
	private Long eventId;
	
	private EveEvent event;
	
	private String title;
	
	private Date startTime;
	
	private Date endTime;
	
	
	
	public String getTitle() {
		if (event!=null) {
			return event.getTitle();
		}
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	public Date getStartTime() {
		if (event!=null) {
			return event.getStartTime();
		}
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	public Date getEndTime() {
		if (event!=null) {
			return event.getEndTime();
		}
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	private String cmdName;
	
	
	public String getCmdName() {
		return cmdName;
	}

	public void setCmdName(String cmdName) {
		this.cmdName = cmdName;
	}

	public EveEvent getEvent() {
		return event;
	}

	public void setEvent(EveEvent event) {
		this.event = event;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_price.price_id
	 * @return  the value of mk_cmd_price.price_id
	 * @mbg.generated
	 */
	public Long getPriceId() {
		return priceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_price.price_id
	 * @param priceId  the value for mk_cmd_price.price_id
	 * @mbg.generated
	 */
	public void setPriceId(Long priceId) {
		this.priceId = priceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_price.cmd_id
	 * @return  the value of mk_cmd_price.cmd_id
	 * @mbg.generated
	 */
	public Long getCmdId() {
		return cmdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_price.cmd_id
	 * @param cmdId  the value for mk_cmd_price.cmd_id
	 * @mbg.generated
	 */
	public void setCmdId(Long cmdId) {
		this.cmdId = cmdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_price.price
	 * @return  the value of mk_cmd_price.price
	 * @mbg.generated
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_price.price
	 * @param price  the value for mk_cmd_price.price
	 * @mbg.generated
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_price.status
	 * @return  the value of mk_cmd_price.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_price.status
	 * @param status  the value for mk_cmd_price.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_price.price_type
	 * @return  the value of mk_cmd_price.price_type
	 * @mbg.generated
	 */
	public Integer getPriceType() {
		return priceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_price.price_type
	 * @param priceType  the value for mk_cmd_price.price_type
	 * @mbg.generated
	 */
	public void setPriceType(Integer priceType) {
		this.priceType = priceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_cmd_price.event_id
	 * @return  the value of mk_cmd_price.event_id
	 * @mbg.generated
	 */
	public Long getEventId() {
		return eventId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_cmd_price.event_id
	 * @param eventId  the value for mk_cmd_price.event_id
	 * @mbg.generated
	 */
	public void setEventId(Long eventId) {
		this.eventId = eventId;
	}
}