package com.voidwhile.market.entity;

public class CmdSpecification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_specification.sft_id
     *
     * @mbg.generated
     */
    private Long sftId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_specification.cmd_id
     *
     * @mbg.generated
     */
    private Long cmdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_specification.cfg_sft_id
     *
     * @mbg.generated
     */
    private Long cfgSftId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_specification.sft_val
     *
     * @mbg.generated
     */
    private String sftVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_cmd_specification.orders
     *
     * @mbg.generated
     */
    private Integer orders;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_specification.sft_id
     *
     * @return the value of mk_cmd_specification.sft_id
     *
     * @mbg.generated
     */
    public Long getSftId() {
        return sftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_specification.sft_id
     *
     * @param sftId the value for mk_cmd_specification.sft_id
     *
     * @mbg.generated
     */
    public void setSftId(Long sftId) {
        this.sftId = sftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_specification.cmd_id
     *
     * @return the value of mk_cmd_specification.cmd_id
     *
     * @mbg.generated
     */
    public Long getCmdId() {
        return cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_specification.cmd_id
     *
     * @param cmdId the value for mk_cmd_specification.cmd_id
     *
     * @mbg.generated
     */
    public void setCmdId(Long cmdId) {
        this.cmdId = cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_specification.cfg_sft_id
     *
     * @return the value of mk_cmd_specification.cfg_sft_id
     *
     * @mbg.generated
     */
    public Long getCfgSftId() {
        return cfgSftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_specification.cfg_sft_id
     *
     * @param cfgSftId the value for mk_cmd_specification.cfg_sft_id
     *
     * @mbg.generated
     */
    public void setCfgSftId(Long cfgSftId) {
        this.cfgSftId = cfgSftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_specification.sft_val
     *
     * @return the value of mk_cmd_specification.sft_val
     *
     * @mbg.generated
     */
    public String getSftVal() {
        return sftVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_specification.sft_val
     *
     * @param sftVal the value for mk_cmd_specification.sft_val
     *
     * @mbg.generated
     */
    public void setSftVal(String sftVal) {
        this.sftVal = sftVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_cmd_specification.orders
     *
     * @return the value of mk_cmd_specification.orders
     *
     * @mbg.generated
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_cmd_specification.orders
     *
     * @param orders the value for mk_cmd_specification.orders
     *
     * @mbg.generated
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }
}