package com.voidwhile.market.entity;

public class MbeAddress {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_mbe_address.addr_id
	 * @mbg.generated
	 */
	private Long addrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_mbe_address.titile
	 * @mbg.generated
	 */
	private String titile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_mbe_address.real_name
	 * @mbg.generated
	 */
	private String realName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_mbe_address.member_id
	 * @mbg.generated
	 */
	private Long memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_mbe_address.address
	 * @mbg.generated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_mbe_address.mp
	 * @mbg.generated
	 */
	private String mp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_mbe_address.telphone
	 * @mbg.generated
	 */
	private String telphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_mbe_address.is_default
	 * @mbg.generated
	 */
	private Boolean isDefault;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_mbe_address.addr_id
	 * @return  the value of mk_mbe_address.addr_id
	 * @mbg.generated
	 */
	public Long getAddrId() {
		return addrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_mbe_address.addr_id
	 * @param addrId  the value for mk_mbe_address.addr_id
	 * @mbg.generated
	 */
	public void setAddrId(Long addrId) {
		this.addrId = addrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_mbe_address.titile
	 * @return  the value of mk_mbe_address.titile
	 * @mbg.generated
	 */
	public String getTitile() {
		return titile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_mbe_address.titile
	 * @param titile  the value for mk_mbe_address.titile
	 * @mbg.generated
	 */
	public void setTitile(String titile) {
		this.titile = titile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_mbe_address.real_name
	 * @return  the value of mk_mbe_address.real_name
	 * @mbg.generated
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_mbe_address.real_name
	 * @param realName  the value for mk_mbe_address.real_name
	 * @mbg.generated
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_mbe_address.member_id
	 * @return  the value of mk_mbe_address.member_id
	 * @mbg.generated
	 */
	public Long getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_mbe_address.member_id
	 * @param memberId  the value for mk_mbe_address.member_id
	 * @mbg.generated
	 */
	public void setMemberId(Long memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_mbe_address.address
	 * @return  the value of mk_mbe_address.address
	 * @mbg.generated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_mbe_address.address
	 * @param address  the value for mk_mbe_address.address
	 * @mbg.generated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_mbe_address.mp
	 * @return  the value of mk_mbe_address.mp
	 * @mbg.generated
	 */
	public String getMp() {
		return mp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_mbe_address.mp
	 * @param mp  the value for mk_mbe_address.mp
	 * @mbg.generated
	 */
	public void setMp(String mp) {
		this.mp = mp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_mbe_address.telphone
	 * @return  the value of mk_mbe_address.telphone
	 * @mbg.generated
	 */
	public String getTelphone() {
		return telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_mbe_address.telphone
	 * @param telphone  the value for mk_mbe_address.telphone
	 * @mbg.generated
	 */
	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_mbe_address.is_default
	 * @return  the value of mk_mbe_address.is_default
	 * @mbg.generated
	 */
	public Boolean getIsDefault() {
		return isDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_mbe_address.is_default
	 * @param isDefault  the value for mk_mbe_address.is_default
	 * @mbg.generated
	 */
	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}
}