package com.voidwhile.market.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MbeCollect {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_mbe_collect.collect_id
	 * @mbg.generated
	 */
	private Long collectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_mbe_collect.mc_member_id
	 * @mbg.generated
	 */
	private Long mcMemberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_mbe_collect.cmd_id
	 * @mbg.generated
	 */
	private Long cmdId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_mbe_collect.collect_time
	 * @mbg.generated
	 */
	private Date collectTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_mbe_collect.collect_id
	 * @return  the value of mk_mbe_collect.collect_id
	 * @mbg.generated
	 */
	public Long getCollectId() {
		return collectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_mbe_collect.collect_id
	 * @param collectId  the value for mk_mbe_collect.collect_id
	 * @mbg.generated
	 */
	public void setCollectId(Long collectId) {
		this.collectId = collectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_mbe_collect.mc_member_id
	 * @return  the value of mk_mbe_collect.mc_member_id
	 * @mbg.generated
	 */
	public Long getMcMemberId() {
		return mcMemberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_mbe_collect.mc_member_id
	 * @param mcMemberId  the value for mk_mbe_collect.mc_member_id
	 * @mbg.generated
	 */
	public void setMcMemberId(Long mcMemberId) {
		this.mcMemberId = mcMemberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_mbe_collect.cmd_id
	 * @return  the value of mk_mbe_collect.cmd_id
	 * @mbg.generated
	 */
	public Long getCmdId() {
		return cmdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_mbe_collect.cmd_id
	 * @param cmdId  the value for mk_mbe_collect.cmd_id
	 * @mbg.generated
	 */
	public void setCmdId(Long cmdId) {
		this.cmdId = cmdId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_mbe_collect.collect_time
	 * @return  the value of mk_mbe_collect.collect_time
	 * @mbg.generated
	 */
	public Date getCollectTime() {
		return collectTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_mbe_collect.collect_time
	 * @param collectTime  the value for mk_mbe_collect.collect_time
	 * @mbg.generated
	 */
	public void setCollectTime(Date collectTime) {
		this.collectTime = collectTime;
	}

	private String cmdName;

	private String cmdCode;
	
	private BigDecimal price;
	
	private BigDecimal eventPrice;
	
	private String imgPath;


	public String getCmdName() {
		return cmdName;
	}

	public void setCmdName(String cmdName) {
		this.cmdName = cmdName;
	}

	public String getCmdCode() {
		return cmdCode;
	}

	public void setCmdCode(String cmdCode) {
		this.cmdCode = cmdCode;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getEventPrice() {
		return eventPrice;
	}

	public void setEventPrice(BigDecimal eventPrice) {
		this.eventPrice = eventPrice;
	}

	public String getImgPath() {
		return imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

    
}