package com.voidwhile.market.entity;

import java.util.Date;

public class MbeCollect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_collect.collect_id
     *
     * @mbg.generated
     */
    private Long collectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_collect.userid
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_collect.cmd_id
     *
     * @mbg.generated
     */
    private Long cmdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_collect.collect_time
     *
     * @mbg.generated
     */
    private Date collectTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_collect.collect_id
     *
     * @return the value of mk_mbe_collect.collect_id
     *
     * @mbg.generated
     */
    public Long getCollectId() {
        return collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_collect.collect_id
     *
     * @param collectId the value for mk_mbe_collect.collect_id
     *
     * @mbg.generated
     */
    public void setCollectId(Long collectId) {
        this.collectId = collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_collect.userid
     *
     * @return the value of mk_mbe_collect.userid
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_collect.userid
     *
     * @param userid the value for mk_mbe_collect.userid
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_collect.cmd_id
     *
     * @return the value of mk_mbe_collect.cmd_id
     *
     * @mbg.generated
     */
    public Long getCmdId() {
        return cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_collect.cmd_id
     *
     * @param cmdId the value for mk_mbe_collect.cmd_id
     *
     * @mbg.generated
     */
    public void setCmdId(Long cmdId) {
        this.cmdId = cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_collect.collect_time
     *
     * @return the value of mk_mbe_collect.collect_time
     *
     * @mbg.generated
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_collect.collect_time
     *
     * @param collectTime the value for mk_mbe_collect.collect_time
     *
     * @mbg.generated
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }
}