package com.voidwhile.market.entity;

import java.util.Date;

public class MbeMemberCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_member_card.card_id
     *
     * @mbg.generated
     */
    private Long cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_member_card.member_code
     *
     * @mbg.generated
     */
    private String memberCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_member_card.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_member_card.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_member_card.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_member_card.linkman
     *
     * @mbg.generated
     */
    private String linkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_member_card.linkmp
     *
     * @mbg.generated
     */
    private String linkmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_member_card.card_id
     *
     * @return the value of mk_mbe_member_card.card_id
     *
     * @mbg.generated
     */
    public Long getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_member_card.card_id
     *
     * @param cardId the value for mk_mbe_member_card.card_id
     *
     * @mbg.generated
     */
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_member_card.member_code
     *
     * @return the value of mk_mbe_member_card.member_code
     *
     * @mbg.generated
     */
    public String getMemberCode() {
        return memberCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_member_card.member_code
     *
     * @param memberCode the value for mk_mbe_member_card.member_code
     *
     * @mbg.generated
     */
    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_member_card.member_id
     *
     * @return the value of mk_mbe_member_card.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_member_card.member_id
     *
     * @param memberId the value for mk_mbe_member_card.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_member_card.score
     *
     * @return the value of mk_mbe_member_card.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_member_card.score
     *
     * @param score the value for mk_mbe_member_card.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_member_card.create_time
     *
     * @return the value of mk_mbe_member_card.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_member_card.create_time
     *
     * @param createTime the value for mk_mbe_member_card.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_member_card.linkman
     *
     * @return the value of mk_mbe_member_card.linkman
     *
     * @mbg.generated
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_member_card.linkman
     *
     * @param linkman the value for mk_mbe_member_card.linkman
     *
     * @mbg.generated
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_member_card.linkmp
     *
     * @return the value of mk_mbe_member_card.linkmp
     *
     * @mbg.generated
     */
    public String getLinkmp() {
        return linkmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_member_card.linkmp
     *
     * @param linkmp the value for mk_mbe_member_card.linkmp
     *
     * @mbg.generated
     */
    public void setLinkmp(String linkmp) {
        this.linkmp = linkmp;
    }
}