package com.voidwhile.market.entity;

import java.util.Date;

public class MbeMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_member.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_member.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_member.passwd
     *
     * @mbg.generated
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_member.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_member.mp
     *
     * @mbg.generated
     */
    private String mp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_mbe_member.last_login_time
     *
     * @mbg.generated
     */
    private Date lastLoginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_member.member_id
     *
     * @return the value of mk_mbe_member.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_member.member_id
     *
     * @param memberId the value for mk_mbe_member.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_member.user_name
     *
     * @return the value of mk_mbe_member.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_member.user_name
     *
     * @param userName the value for mk_mbe_member.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_member.passwd
     *
     * @return the value of mk_mbe_member.passwd
     *
     * @mbg.generated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_member.passwd
     *
     * @param passwd the value for mk_mbe_member.passwd
     *
     * @mbg.generated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_member.real_name
     *
     * @return the value of mk_mbe_member.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_member.real_name
     *
     * @param realName the value for mk_mbe_member.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_member.mp
     *
     * @return the value of mk_mbe_member.mp
     *
     * @mbg.generated
     */
    public String getMp() {
        return mp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_member.mp
     *
     * @param mp the value for mk_mbe_member.mp
     *
     * @mbg.generated
     */
    public void setMp(String mp) {
        this.mp = mp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_mbe_member.last_login_time
     *
     * @return the value of mk_mbe_member.last_login_time
     *
     * @mbg.generated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_mbe_member.last_login_time
     *
     * @param lastLoginTime the value for mk_mbe_member.last_login_time
     *
     * @mbg.generated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
}