package com.voidwhile.market.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class OdrOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_odr_order.order_id
	 * @mbg.generated
	 */
	private Long orderId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_odr_order.order_code
	 * @mbg.generated
	 */
	private String orderCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_odr_order.member_id
	 * @mbg.generated
	 */
	private Long memberId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_odr_order.create_time
	 * @mbg.generated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_odr_order.status
	 * @mbg.generated
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_odr_order.pay_status
	 * @mbg.generated
	 */
	private Integer payStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_odr_order.pay_time
	 * @mbg.generated
	 */
	private Date payTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_odr_order.pay_type
	 * @mbg.generated
	 */
	private Integer payType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_odr_order.addr_id
	 * @mbg.generated
	 */
	private Long addrId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_odr_order.total_amount
	 * @mbg.generated
	 */
	private Double totalAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_odr_order.flowNum
	 * @mbg.generated
	 */
	private String flownum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_odr_order.order_id
	 * @return  the value of mk_odr_order.order_id
	 * @mbg.generated
	 */
	public Long getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_odr_order.order_id
	 * @param orderId  the value for mk_odr_order.order_id
	 * @mbg.generated
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_odr_order.order_code
	 * @return  the value of mk_odr_order.order_code
	 * @mbg.generated
	 */
	public String getOrderCode() {
		return orderCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_odr_order.order_code
	 * @param orderCode  the value for mk_odr_order.order_code
	 * @mbg.generated
	 */
	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_odr_order.member_id
	 * @return  the value of mk_odr_order.member_id
	 * @mbg.generated
	 */
	public Long getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_odr_order.member_id
	 * @param memberId  the value for mk_odr_order.member_id
	 * @mbg.generated
	 */
	public void setMemberId(Long memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_odr_order.create_time
	 * @return  the value of mk_odr_order.create_time
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_odr_order.create_time
	 * @param createTime  the value for mk_odr_order.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_odr_order.status
	 * @return  the value of mk_odr_order.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_odr_order.status
	 * @param status  the value for mk_odr_order.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_odr_order.pay_status
	 * @return  the value of mk_odr_order.pay_status
	 * @mbg.generated
	 */
	public Integer getPayStatus() {
		return payStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_odr_order.pay_status
	 * @param payStatus  the value for mk_odr_order.pay_status
	 * @mbg.generated
	 */
	public void setPayStatus(Integer payStatus) {
		this.payStatus = payStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_odr_order.pay_time
	 * @return  the value of mk_odr_order.pay_time
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_odr_order.pay_time
	 * @param payTime  the value for mk_odr_order.pay_time
	 * @mbg.generated
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_odr_order.pay_type
	 * @return  the value of mk_odr_order.pay_type
	 * @mbg.generated
	 */
	public Integer getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_odr_order.pay_type
	 * @param payType  the value for mk_odr_order.pay_type
	 * @mbg.generated
	 */
	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_odr_order.addr_id
	 * @return  the value of mk_odr_order.addr_id
	 * @mbg.generated
	 */
	public Long getAddrId() {
		return addrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_odr_order.addr_id
	 * @param addrId  the value for mk_odr_order.addr_id
	 * @mbg.generated
	 */
	public void setAddrId(Long addrId) {
		this.addrId = addrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_odr_order.total_amount
	 * @return  the value of mk_odr_order.total_amount
	 * @mbg.generated
	 */
	public Double getTotalAmount() {
		return totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_odr_order.total_amount
	 * @param totalAmount  the value for mk_odr_order.total_amount
	 * @mbg.generated
	 */
	public void setTotalAmount(Double totalAmount) {
		this.totalAmount = totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_odr_order.flowNum
	 * @return  the value of mk_odr_order.flowNum
	 * @mbg.generated
	 */
	public String getFlownum() {
		return flownum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_odr_order.flowNum
	 * @param flownum  the value for mk_odr_order.flowNum
	 * @mbg.generated
	 */
	public void setFlownum(String flownum) {
		this.flownum = flownum;
	}

	private String payTypeName;
	
	private String statusName;

	private MbeMember member;
	
	private MbeAddress addr;
	
	private String linkMan;
	private String address;
	private String phone;
	
	public MbeAddress getAddr() {
		return addr;
	}

	public void setAddr(MbeAddress addr) {
		this.addr = addr;
	}

	public MbeMember getMember() {
		return member;
	}

	public void setMember(MbeMember member) {
		this.member = member;
	}
	
	public String getPayTypeName() {
		return payTypeName;
	}

	public void setPayTypeName(String payTypeName) {
		this.payTypeName = payTypeName;
	}

	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	public String getLinkMan() {
		if (this.addr!=null) {
			return addr.getRealName();
		}
		return linkMan;
	}

	public void setLinkMan(String linkMan) {
		this.linkMan = linkMan;
	}

	public String getAddress() {
		if (this.addr!=null) {
			return this.addr.getAddress();
		}
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		if (this.addr!=null) {
			return this.addr.getMp()==null?this.addr.getMp():this.addr.getTelphone();
		}
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
}