package com.voidwhile.market.entity;

import java.math.BigDecimal;

public class OdrOrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_odr_order_detail.detail_id
     *
     * @mbg.generated
     */
    private Long detailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_odr_order_detail.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_odr_order_detail.cmd_id
     *
     * @mbg.generated
     */
    private Long cmdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_odr_order_detail.price_id
     *
     * @mbg.generated
     */
    private Long priceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_odr_order_detail.quantity
     *
     * @mbg.generated
     */
    private Double quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_odr_order_detail.total_price
     *
     * @mbg.generated
     */
    private Double totalPrice;
    
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_odr_order_detail.detail_id
     *
     * @return the value of mk_odr_order_detail.detail_id
     *
     * @mbg.generated
     */
    public Long getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_odr_order_detail.detail_id
     *
     * @param detailId the value for mk_odr_order_detail.detail_id
     *
     * @mbg.generated
     */
    public void setDetailId(Long detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_odr_order_detail.order_id
     *
     * @return the value of mk_odr_order_detail.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_odr_order_detail.order_id
     *
     * @param orderId the value for mk_odr_order_detail.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_odr_order_detail.cmd_id
     *
     * @return the value of mk_odr_order_detail.cmd_id
     *
     * @mbg.generated
     */
    public Long getCmdId() {
        return cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_odr_order_detail.cmd_id
     *
     * @param cmdId the value for mk_odr_order_detail.cmd_id
     *
     * @mbg.generated
     */
    public void setCmdId(Long cmdId) {
        this.cmdId = cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_odr_order_detail.price_id
     *
     * @return the value of mk_odr_order_detail.price_id
     *
     * @mbg.generated
     */
    public Long getPriceId() {
        return priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_odr_order_detail.price_id
     *
     * @param priceId the value for mk_odr_order_detail.price_id
     *
     * @mbg.generated
     */
    public void setPriceId(Long priceId) {
        this.priceId = priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_odr_order_detail.quantity
     *
     * @return the value of mk_odr_order_detail.quantity
     *
     * @mbg.generated
     */
    public Double getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_odr_order_detail.quantity
     *
     * @param quantity the value for mk_odr_order_detail.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_odr_order_detail.total_price
     *
     * @return the value of mk_odr_order_detail.total_price
     *
     * @mbg.generated
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_odr_order_detail.total_price
     *
     * @param totalPrice the value for mk_odr_order_detail.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
    
    private String cmdName;
    
    private BigDecimal unitPrice;
    
    private CmdPrice cmdPrice;
    
    public BigDecimal getUnitPrice() {
		return unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	public CmdPrice getCmdPrice() {
		return cmdPrice;
	}

	public void setCmdPrice(CmdPrice cmdPrice) {
		this.cmdPrice = cmdPrice;
	}

	public String getCmdName() {
		return cmdName;
	}

	public void setCmdName(String cmdName) {
		this.cmdName = cmdName;
	}

}