package com.voidwhile.market.entity;

public class RepCmdSupplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_rep_cmd_supplier.cmd_supplier_id
     *
     * @mbg.generated
     */
    private Long cmdSupplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_rep_cmd_supplier.cmd_id
     *
     * @mbg.generated
     */
    private Long cmdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_rep_cmd_supplier.supplier_id
     *
     * @mbg.generated
     */
    private Long supplierId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_rep_cmd_supplier.cmd_supplier_id
     *
     * @return the value of mk_rep_cmd_supplier.cmd_supplier_id
     *
     * @mbg.generated
     */
    public Long getCmdSupplierId() {
        return cmdSupplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_rep_cmd_supplier.cmd_supplier_id
     *
     * @param cmdSupplierId the value for mk_rep_cmd_supplier.cmd_supplier_id
     *
     * @mbg.generated
     */
    public void setCmdSupplierId(Long cmdSupplierId) {
        this.cmdSupplierId = cmdSupplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_rep_cmd_supplier.cmd_id
     *
     * @return the value of mk_rep_cmd_supplier.cmd_id
     *
     * @mbg.generated
     */
    public Long getCmdId() {
        return cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_rep_cmd_supplier.cmd_id
     *
     * @param cmdId the value for mk_rep_cmd_supplier.cmd_id
     *
     * @mbg.generated
     */
    public void setCmdId(Long cmdId) {
        this.cmdId = cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_rep_cmd_supplier.supplier_id
     *
     * @return the value of mk_rep_cmd_supplier.supplier_id
     *
     * @mbg.generated
     */
    public Long getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_rep_cmd_supplier.supplier_id
     *
     * @param supplierId the value for mk_rep_cmd_supplier.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplierId(Long supplierId) {
        this.supplierId = supplierId;
    }
}