package com.voidwhile.market.entity;

import java.util.Date;

public class RepInventory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_rep_inventory.inventory_id
     *
     * @mbg.generated
     */
    private Long inventoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_rep_inventory.cmd_id
     *
     * @mbg.generated
     */
    private Long cmdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_rep_inventory.stock
     *
     * @mbg.generated
     */
    private Double stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_rep_inventory.lcd
     *
     * @mbg.generated
     */
    private Date lcd;
    
    private String cmdName;
	
	private String brandName;
	
	private String cmdCode;
	
	private String cmdStatus;
	

	public String getCmdCode() {
		return cmdCode;
	}

	public void setCmdCode(String cmdCode) {
		this.cmdCode = cmdCode;
	}

	public String getCmdStatus() {
		return cmdStatus;
	}

	public void setCmdStatus(String cmdStatus) {
		this.cmdStatus = cmdStatus;
	}

	public String getCmdName() {
		return cmdName;
	}

	public void setCmdName(String cmdName) {
		this.cmdName = cmdName;
	}

	public String getBrandName() {
		return brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_rep_inventory.inventory_id
     *
     * @return the value of mk_rep_inventory.inventory_id
     *
     * @mbg.generated
     */
    public Long getInventoryId() {
        return inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_rep_inventory.inventory_id
     *
     * @param inventoryId the value for mk_rep_inventory.inventory_id
     *
     * @mbg.generated
     */
    public void setInventoryId(Long inventoryId) {
        this.inventoryId = inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_rep_inventory.cmd_id
     *
     * @return the value of mk_rep_inventory.cmd_id
     *
     * @mbg.generated
     */
    public Long getCmdId() {
        return cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_rep_inventory.cmd_id
     *
     * @param cmdId the value for mk_rep_inventory.cmd_id
     *
     * @mbg.generated
     */
    public void setCmdId(Long cmdId) {
        this.cmdId = cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_rep_inventory.stock
     *
     * @return the value of mk_rep_inventory.stock
     *
     * @mbg.generated
     */
    public Double getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_rep_inventory.stock
     *
     * @param stock the value for mk_rep_inventory.stock
     *
     * @mbg.generated
     */
    public void setStock(Double stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_rep_inventory.lcd
     *
     * @return the value of mk_rep_inventory.lcd
     *
     * @mbg.generated
     */
    public Date getLcd() {
        return lcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_rep_inventory.lcd
     *
     * @param lcd the value for mk_rep_inventory.lcd
     *
     * @mbg.generated
     */
    public void setLcd(Date lcd) {
        this.lcd = lcd;
    }
}