package com.voidwhile.market.entity;

import java.util.Date;

public class RepSupplier {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_supplier.supplier_id
	 * @mbg.generated
	 */
	private Long supplierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_supplier.supplier_name
	 * @mbg.generated
	 */
	private String supplierName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_supplier.link_man
	 * @mbg.generated
	 */
	private String linkMan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_supplier.link_mp
	 * @mbg.generated
	 */
	private String linkMp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_supplier.address
	 * @mbg.generated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_supplier.description
	 * @mbg.generated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_supplier.server_start
	 * @mbg.generated
	 */
	private Date serverStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_supplier.status
	 * @mbg.generated
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_supplier.supplier_id
	 * @return  the value of mk_rep_supplier.supplier_id
	 * @mbg.generated
	 */
	public Long getSupplierId() {
		return supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_supplier.supplier_id
	 * @param supplierId  the value for mk_rep_supplier.supplier_id
	 * @mbg.generated
	 */
	public void setSupplierId(Long supplierId) {
		this.supplierId = supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_supplier.supplier_name
	 * @return  the value of mk_rep_supplier.supplier_name
	 * @mbg.generated
	 */
	public String getSupplierName() {
		return supplierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_supplier.supplier_name
	 * @param supplierName  the value for mk_rep_supplier.supplier_name
	 * @mbg.generated
	 */
	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_supplier.link_man
	 * @return  the value of mk_rep_supplier.link_man
	 * @mbg.generated
	 */
	public String getLinkMan() {
		return linkMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_supplier.link_man
	 * @param linkMan  the value for mk_rep_supplier.link_man
	 * @mbg.generated
	 */
	public void setLinkMan(String linkMan) {
		this.linkMan = linkMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_supplier.link_mp
	 * @return  the value of mk_rep_supplier.link_mp
	 * @mbg.generated
	 */
	public String getLinkMp() {
		return linkMp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_supplier.link_mp
	 * @param linkMp  the value for mk_rep_supplier.link_mp
	 * @mbg.generated
	 */
	public void setLinkMp(String linkMp) {
		this.linkMp = linkMp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_supplier.address
	 * @return  the value of mk_rep_supplier.address
	 * @mbg.generated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_supplier.address
	 * @param address  the value for mk_rep_supplier.address
	 * @mbg.generated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_supplier.description
	 * @return  the value of mk_rep_supplier.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_supplier.description
	 * @param description  the value for mk_rep_supplier.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_supplier.server_start
	 * @return  the value of mk_rep_supplier.server_start
	 * @mbg.generated
	 */
	public Date getServerStart() {
		return serverStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_supplier.server_start
	 * @param serverStart  the value for mk_rep_supplier.server_start
	 * @mbg.generated
	 */
	public void setServerStart(Date serverStart) {
		this.serverStart = serverStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_supplier.status
	 * @return  the value of mk_rep_supplier.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_supplier.status
	 * @param status  the value for mk_rep_supplier.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}