package com.voidwhile.market.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class RepTransact {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_transact.trans_id
	 * @mbg.generated
	 */
	private Long transId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_transact.inventory_id
	 * @mbg.generated
	 */
	private Long inventoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_transact.amount
	 * @mbg.generated
	 */
	private Double amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_transact.trans_type
	 * @mbg.generated
	 */
	private Integer transType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_transact.trans_time
	 * @mbg.generated
	 */
	private Date transTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_transact.supplier_id
	 * @mbg.generated
	 */
	private Long supplierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_transact.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_transact.brand_id
	 * @mbg.generated
	 */
	private Long brandId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_transact.unit_price
	 * @mbg.generated
	 */
	private Double unitPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mk_rep_transact.fcd
	 * @mbg.generated
	 */
	private Date fcd;
	
	private String supplierName;
	private String brandName;
	private String realName;
	private String cmdName;
	
	
	
	
	public String getCmdName() {
		return cmdName;
	}

	public void setCmdName(String cmdName) {
		this.cmdName = cmdName;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getBrandName() {
		return brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_transact.trans_id
	 * @return  the value of mk_rep_transact.trans_id
	 * @mbg.generated
	 */
	public Long getTransId() {
		return transId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_transact.trans_id
	 * @param transId  the value for mk_rep_transact.trans_id
	 * @mbg.generated
	 */
	public void setTransId(Long transId) {
		this.transId = transId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_transact.inventory_id
	 * @return  the value of mk_rep_transact.inventory_id
	 * @mbg.generated
	 */
	public Long getInventoryId() {
		return inventoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_transact.inventory_id
	 * @param inventoryId  the value for mk_rep_transact.inventory_id
	 * @mbg.generated
	 */
	public void setInventoryId(Long inventoryId) {
		this.inventoryId = inventoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_transact.amount
	 * @return  the value of mk_rep_transact.amount
	 * @mbg.generated
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_transact.amount
	 * @param amount  the value for mk_rep_transact.amount
	 * @mbg.generated
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_transact.trans_type
	 * @return  the value of mk_rep_transact.trans_type
	 * @mbg.generated
	 */
	public Integer getTransType() {
		return transType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_transact.trans_type
	 * @param transType  the value for mk_rep_transact.trans_type
	 * @mbg.generated
	 */
	public void setTransType(Integer transType) {
		this.transType = transType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_transact.trans_time
	 * @return  the value of mk_rep_transact.trans_time
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	public Date getTransTime() {
		return transTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_transact.trans_time
	 * @param transTime  the value for mk_rep_transact.trans_time
	 * @mbg.generated
	 */
	public void setTransTime(Date transTime) {
		this.transTime = transTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_transact.supplier_id
	 * @return  the value of mk_rep_transact.supplier_id
	 * @mbg.generated
	 */
	public Long getSupplierId() {
		return supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_transact.supplier_id
	 * @param supplierId  the value for mk_rep_transact.supplier_id
	 * @mbg.generated
	 */
	public void setSupplierId(Long supplierId) {
		this.supplierId = supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_transact.user_id
	 * @return  the value of mk_rep_transact.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_transact.user_id
	 * @param userId  the value for mk_rep_transact.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_transact.brand_id
	 * @return  the value of mk_rep_transact.brand_id
	 * @mbg.generated
	 */
	public Long getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_transact.brand_id
	 * @param brandId  the value for mk_rep_transact.brand_id
	 * @mbg.generated
	 */
	public void setBrandId(Long brandId) {
		this.brandId = brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_transact.unit_price
	 * @return  the value of mk_rep_transact.unit_price
	 * @mbg.generated
	 */
	public Double getUnitPrice() {
		return unitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_transact.unit_price
	 * @param unitPrice  the value for mk_rep_transact.unit_price
	 * @mbg.generated
	 */
	public void setUnitPrice(Double unitPrice) {
		this.unitPrice = unitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mk_rep_transact.fcd
	 * @return  the value of mk_rep_transact.fcd
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	public Date getFcd() {
		return fcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mk_rep_transact.fcd
	 * @param fcd  the value for mk_rep_transact.fcd
	 * @mbg.generated
	 */
	public void setFcd(Date fcd) {
		this.fcd = fcd;
	}
}