package com.voidwhile.market.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RunRecommend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_run_recommend.recom_id
     *
     * @mbg.generated
     */
    private Long recomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_run_recommend.rr_cmd_id
     *
     * @mbg.generated
     */
    private Long rrCmdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_run_recommend.recom_day
     *
     * @mbg.generated
     */
    private Date recomDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mk_run_recommend.intro
     *
     * @mbg.generated
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_run_recommend.recom_id
     *
     * @return the value of mk_run_recommend.recom_id
     *
     * @mbg.generated
     */
    public Long getRecomId() {
        return recomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_run_recommend.recom_id
     *
     * @param recomId the value for mk_run_recommend.recom_id
     *
     * @mbg.generated
     */
    public void setRecomId(Long recomId) {
        this.recomId = recomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_run_recommend.rr_cmd_id
     *
     * @return the value of mk_run_recommend.rr_cmd_id
     *
     * @mbg.generated
     */
    public Long getRrCmdId() {
        return rrCmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_run_recommend.rr_cmd_id
     *
     * @param rrCmdId the value for mk_run_recommend.rr_cmd_id
     *
     * @mbg.generated
     */
    public void setRrCmdId(Long rrCmdId) {
        this.rrCmdId = rrCmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_run_recommend.recom_day
     *
     * @return the value of mk_run_recommend.recom_day
     *
     * @mbg.generated
     */
    public Date getRecomDay() {
        return recomDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_run_recommend.recom_day
     *
     * @param recomDay the value for mk_run_recommend.recom_day
     *
     * @mbg.generated
     */
    public void setRecomDay(Date recomDay) {
        this.recomDay = recomDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mk_run_recommend.intro
     *
     * @return the value of mk_run_recommend.intro
     *
     * @mbg.generated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mk_run_recommend.intro
     *
     * @param intro the value for mk_run_recommend.intro
     *
     * @mbg.generated
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }
    
    private BigDecimal price;
    private String cmdName;

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getCmdName() {
		return cmdName;
	}

	public void setCmdName(String cmdName) {
		this.cmdName = cmdName;
	}
}