package com.voidwhile.market.entity;

import java.util.Date;

public class WechatUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.headimg
     *
     * @mbg.generated
     */
    private String headimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.realname
     *
     * @mbg.generated
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.wnickname
     *
     * @mbg.generated
     */
    private String wnickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.provUuid
     *
     * @mbg.generated
     */
    private String provuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.cityUuid
     *
     * @mbg.generated
     */
    private String cityuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.countyUuid
     *
     * @mbg.generated
     */
    private String countyuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.cardImg
     *
     * @mbg.generated
     */
    private String cardimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.subscribe
     *
     * @mbg.generated
     */
    private Integer subscribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.language
     *
     * @mbg.generated
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.headimgurl
     *
     * @mbg.generated
     */
    private String headimgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.subscribe_time
     *
     * @mbg.generated
     */
    private String subscribeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.groupid
     *
     * @mbg.generated
     */
    private String groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.appid
     *
     * @mbg.generated
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.recommOpenid
     *
     * @mbg.generated
     */
    private String recommopenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_wechat_user.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.openid
     *
     * @return the value of wx_wechat_user.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.openid
     *
     * @param openid the value for wx_wechat_user.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.headimg
     *
     * @return the value of wx_wechat_user.headimg
     *
     * @mbg.generated
     */
    public String getHeadimg() {
        return headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.headimg
     *
     * @param headimg the value for wx_wechat_user.headimg
     *
     * @mbg.generated
     */
    public void setHeadimg(String headimg) {
        this.headimg = headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.realname
     *
     * @return the value of wx_wechat_user.realname
     *
     * @mbg.generated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.realname
     *
     * @param realname the value for wx_wechat_user.realname
     *
     * @mbg.generated
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.wnickname
     *
     * @return the value of wx_wechat_user.wnickname
     *
     * @mbg.generated
     */
    public String getWnickname() {
        return wnickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.wnickname
     *
     * @param wnickname the value for wx_wechat_user.wnickname
     *
     * @mbg.generated
     */
    public void setWnickname(String wnickname) {
        this.wnickname = wnickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.nickname
     *
     * @return the value of wx_wechat_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.nickname
     *
     * @param nickname the value for wx_wechat_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.mobile
     *
     * @return the value of wx_wechat_user.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.mobile
     *
     * @param mobile the value for wx_wechat_user.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.provUuid
     *
     * @return the value of wx_wechat_user.provUuid
     *
     * @mbg.generated
     */
    public String getProvuuid() {
        return provuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.provUuid
     *
     * @param provuuid the value for wx_wechat_user.provUuid
     *
     * @mbg.generated
     */
    public void setProvuuid(String provuuid) {
        this.provuuid = provuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.cityUuid
     *
     * @return the value of wx_wechat_user.cityUuid
     *
     * @mbg.generated
     */
    public String getCityuuid() {
        return cityuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.cityUuid
     *
     * @param cityuuid the value for wx_wechat_user.cityUuid
     *
     * @mbg.generated
     */
    public void setCityuuid(String cityuuid) {
        this.cityuuid = cityuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.countyUuid
     *
     * @return the value of wx_wechat_user.countyUuid
     *
     * @mbg.generated
     */
    public String getCountyuuid() {
        return countyuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.countyUuid
     *
     * @param countyuuid the value for wx_wechat_user.countyUuid
     *
     * @mbg.generated
     */
    public void setCountyuuid(String countyuuid) {
        this.countyuuid = countyuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.address
     *
     * @return the value of wx_wechat_user.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.address
     *
     * @param address the value for wx_wechat_user.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.cardImg
     *
     * @return the value of wx_wechat_user.cardImg
     *
     * @mbg.generated
     */
    public String getCardimg() {
        return cardimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.cardImg
     *
     * @param cardimg the value for wx_wechat_user.cardImg
     *
     * @mbg.generated
     */
    public void setCardimg(String cardimg) {
        this.cardimg = cardimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.createtime
     *
     * @return the value of wx_wechat_user.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.createtime
     *
     * @param createtime the value for wx_wechat_user.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.content
     *
     * @return the value of wx_wechat_user.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.content
     *
     * @param content the value for wx_wechat_user.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.password
     *
     * @return the value of wx_wechat_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.password
     *
     * @param password the value for wx_wechat_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.subscribe
     *
     * @return the value of wx_wechat_user.subscribe
     *
     * @mbg.generated
     */
    public Integer getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.subscribe
     *
     * @param subscribe the value for wx_wechat_user.subscribe
     *
     * @mbg.generated
     */
    public void setSubscribe(Integer subscribe) {
        this.subscribe = subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.sex
     *
     * @return the value of wx_wechat_user.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.sex
     *
     * @param sex the value for wx_wechat_user.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.city
     *
     * @return the value of wx_wechat_user.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.city
     *
     * @param city the value for wx_wechat_user.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.country
     *
     * @return the value of wx_wechat_user.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.country
     *
     * @param country the value for wx_wechat_user.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.province
     *
     * @return the value of wx_wechat_user.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.province
     *
     * @param province the value for wx_wechat_user.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.language
     *
     * @return the value of wx_wechat_user.language
     *
     * @mbg.generated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.language
     *
     * @param language the value for wx_wechat_user.language
     *
     * @mbg.generated
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.headimgurl
     *
     * @return the value of wx_wechat_user.headimgurl
     *
     * @mbg.generated
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.headimgurl
     *
     * @param headimgurl the value for wx_wechat_user.headimgurl
     *
     * @mbg.generated
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.subscribe_time
     *
     * @return the value of wx_wechat_user.subscribe_time
     *
     * @mbg.generated
     */
    public String getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.subscribe_time
     *
     * @param subscribeTime the value for wx_wechat_user.subscribe_time
     *
     * @mbg.generated
     */
    public void setSubscribeTime(String subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.groupid
     *
     * @return the value of wx_wechat_user.groupid
     *
     * @mbg.generated
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.groupid
     *
     * @param groupid the value for wx_wechat_user.groupid
     *
     * @mbg.generated
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.appid
     *
     * @return the value of wx_wechat_user.appid
     *
     * @mbg.generated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.appid
     *
     * @param appid the value for wx_wechat_user.appid
     *
     * @mbg.generated
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.recommOpenid
     *
     * @return the value of wx_wechat_user.recommOpenid
     *
     * @mbg.generated
     */
    public String getRecommopenid() {
        return recommopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.recommOpenid
     *
     * @param recommopenid the value for wx_wechat_user.recommOpenid
     *
     * @mbg.generated
     */
    public void setRecommopenid(String recommopenid) {
        this.recommopenid = recommopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.remark
     *
     * @return the value of wx_wechat_user.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.remark
     *
     * @param remark the value for wx_wechat_user.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_wechat_user.member_id
     *
     * @return the value of wx_wechat_user.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_wechat_user.member_id
     *
     * @param memberId the value for wx_wechat_user.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }
}